<a href="https://colab.research.google.com/github/quelrodrigues/analise-lunar/blob/Luana-C/Miss%C3%A3o_compartilhada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!git clone https://github.com/quelrodrigues/analise-lunar.git

fatal: destination path 'analise-lunar' already exists and is not an empty directory.

In [4]:
!pip install numpy matplotlib keras

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (3.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras) (0.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)

In [5]:
import pandas as pd

In [8]:
#Quero que o pandas leia o dado
df_lua = pd.read_csv('/content/analise-lunar/Moonlanding.csv')
display(df_lua)

,Mission,Spacecraft,Launch Date,Carrier Rocket,Operator,Mission Type,Outcome,Additional Information
0,Pioneer 0 (Able I),Pioneer 0,17-Aug-58,Thor DM-18 Able I,United States USAF,Orbiter,Launch failure,First attempted launch beyond Earth orbit; fai...
1,Luna E-1 No.1,Luna E-1 No.1,23-Sep-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; rocket disintegrated due to e...
2,Pioneer 1 (Able II),Pioneer 1,11-Oct-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
3,Luna E-1 No.2,Luna E-1 No.2,11-Oct-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; carrier rocket exploded due t...
4,Pioneer 2 (Able III),Pioneer 2,08-Nov-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
...,...,...,...,...,...,...,...,...
161,Peregrine Mission One,Peregrine,08-Jan-24,Vulcan Centaur VC2,Astrobotic Technology,Lander,Spacecraft failure,Part of CLPS. Peregrine lander's reaction thru...
162,Peregrine Mission One,Colmena ? 5,08-Jan-24,Vulcan Centaur VC2,UNAM,Rovers,Precluded,Part of CLPS. Peregrine lander's reaction thru...
163,Peregrine Mission One,Iris,08-Jan-24,Vulcan Centaur VC2,CMU,Rover,Precluded,Part of CLPS. Peregrine lander's reaction thru...
164,IM-1,Nova-C Odysseus,14-Feb-24,Falcon 9 B5,Intuitive Machines,Lander,Operational,First Nova-C mission. Payloads successfully de...
165,IM-1,EagleCam,14-Feb-24,Falcon 9 B5,ERAU,Deployable camera (semi hard lander),Awaiting Deployment,First Nova-C mission. Payloads successfully de...

In [10]:
#solução do desafio Aluno1
#tarefa1
display(df_lua['Mission Type'].value_counts())

#tarefa2
display(df_lua['Operator'].value_counts())

Mission Type
Orbiter                                 59
Lander                                  40
Flyby                                   31
Impactor                                15
Rover                                    6
Lander,Sample Return                     2
Orbiter,Lander,Rover                     2
Flybys                                   2
Crewed orbiter                           1
Flyby / Impactor (post mission)          1
Relay Satellite                          1
Launch Vehicle                           1
Sample Return                            1
Lander                                   1
Hopper                                   1
Rovers                                   1
Deployable camera (semi hard lander)     1
Name: count, dtype: int64

Operator
United States NASA                   61
Soviet Union Lavochkin               39
Soviet Union OKB-1                   15
China CNSA                           15
Japan JAXA                            5
India ISRO                            4
Japan ISAS                            3
European Union ESA                    2
Tomy / JAXA / Doshisha University     2
United States Hughes                  1
United States USAF/NASA               1
Japan United States ISAS/NASA         1
United States USAF                    1
Luxembourg LuxSpace                   1
Israel SpaceIL                        1
Italy ASI                             1
South Korea KARI                      1
United States Fluid & Reason          1
Japan ispace                          1
Japan Tomy/JAXA/Dodai                 1
United States Lockheed Martin         1
UAE UAESA/MBRSC                       1
Russia Roscosmos                      1
JAXA                                  1
Astrobotic Technology                 1
UNAM                                  1
CMU                                   1
Intuitive Machines                    1
ERAU                                  1
Name: count, dtype: int64

In [12]:
#aluno2
#tarefa1
display(df_lua['Carrier Rocket'].value_counts())
#Tarefa2
display(df_lua['Spacecraft'].value_counts())

Carrier Rocket
Proton-K/D                  24
Molniya-M                   12
SLS Block 1                 11
Saturn V                    10
Luna                         9
Atlas LV-3 Agena-B           6
Atlas SLV-3 Agena-D          5
Molniya-L                    5
Long March 3C                4
Atlas LV-3C Centaur-D        4
Falcon 9 Block 5             4
Long March 3B                4
Long March 5                 4
Thor DM-18 Able I            3
  H-IIA                      3
Vulcan Centaur VC2           3
H-IIA 2022                   3
Atlas-D Able                 3
Atlas SLV-3C Centaur-D       3
Molniya                      3
Long March 4C                3
Juno II                      2
Delta E1                     2
Falcon 9                     2
Delta II 7925                2
PSLV-XL C11                  2
Atlas V 401                  2
Falcon 9 B5                  2
Delta 1913                   1
N1                           1
Delta II 7925-10             1
Delta II 6925                1
Mu-4S-II                     1
Mu-3S-II                     1
Delta 2914                   1
Atlas SLV-3D Centaur-D1A     1
Athena II                    1
Titan II (23)G Star-37FM     1
Delta II 7921H               1
Delta II 7920H               1
Long March 3A                1
M-V                          1
Delta II 7425-10             1
Ariane 5G                    1
Delta II 7925-10L            1
Delta II 7925-11L            1
Proton-K/DM3                 1
LVM3 M1                      1
Minotaur V                   1
Falcon 9 Full Thrust         1
Electron                     1
Ariane 5 ECA                 1
LVM3 M4                      1
Soyuz-2.1b/Fregat            1
Name: count, dtype: int64

Spacecraft
Pioneer 0          1
Luna E-1 No.1      1
Pioneer 1          1
Luna E-1 No.2      1
Pioneer 2          1
                  ..
Peregrine          1
Colmena ? 5        1
Iris               1
Nova-C Odysseus    1
EagleCam           1
Name: count, Length: 166, dtype: int64